### ISSUE TITLE
Back-to-content fails in GIT-flavored markdown

### ISSUE THREAD

**Issue by aguarino77** [lijunle/Vsxmd#20]
Hi, this is just to mention that `[^](...)` will fail to render in GIT-flavoured markdown, because it will be interpreted as an mathematical sign. (see attachemnt).
It's not a serious problem, anyhow.
![screen shot 2015-09-29 at 15 21 28](https://cloud.githubusercontent.com/assets/7809076/10165135/d3759408-66bd-11e5-905b-8a653f3c07bb.png)

My current fix  is to find-replace with [<].

**Comment by lijunle** [comment]
Hi, are you using Github? Which application are you using?

**Comment by aguarino77** [comment]
We have the repositories on an internal gitlab (it’s a git on premise), you can see it at gitlab.com <http://gitlab.com/>.
Special MD features are explained at GitLab Flavored Markdown <https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCgQFjABahUKEwj2t97PrZzIAhVGOhQKHeytDQk&url=https://gitlab.com/gitlab-org/gitlab-ce/blob/6-4-stable/doc/markdown/markdown.md&usg=AFQjCNF3psBNH276q0782rYhp0A60gpBvQ&sig2=3QJ6BvAsdzcJRWamtPMatQ>

**Comment by lijunle** [comment]
I created a public [snippet](https://gitlab.com/snippets/8990) on GitLab.

I am sorry to say that, GitLab has it own anchor location parsing engine, which is not compatible with the standard one. Click on the anchors generated by Vsxmd will break the URL. :cry: 

Are you using the anchor navigation feature provided by Vsxmd. I am thinking about adding a switch to opt-out the anchor navigation generation.

How do you think about this?

**Comment by aguarino77** [comment]
Anchor navigation is really a cool feature. I think that optionally modifying to [<] instead of [#] will work. It’s less pretty, but working.

**Comment by lijunle** [comment]
OK, I am actually talking about another issue.

I understand that, each git hosting website has its own flavor Markdown syntax. That is a trivial change to make `^` to other characters. 

But, another problem is, I have not tested the features on GitLab. So, I am doing feature testing on GitLab, and find a bigger problem - the anchors are not handled correctly in GitLab. If you click on a method, then look on the URL, it is changed to a wrong URL. 

I need more time to investigate this problem and do round feature testing on GitLab.

**Comment by aguarino77** [comment]
Sorry, I did not notice this. You are right, the links work, the URL is wrong. Let me know if I can help

**Comment by lijunle** [comment]
Gitlab is [using](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/vendor/assets/javascripts/jquery.history.js) [History.js](https://github.com/browserstate/history.js) for hash history management.

There is two related bugs reporting in History.js:

- https://github.com/browserstate/history.js/issues/124
- https://github.com/browserstate/history.js/issues/198

**Comment by lijunle** [comment]
@aguarino77 

I have released [v1.1.0](https://www.nuget.org/packages/Vsxmd/1.1.0) to resolve these two problems.

- The *back to contents* sign is changed to `=`.
- The `.` sign in href anchor is escaped as `-` to avoid History.js issue.
