### ISSUE TITLE
Configuring output file path

### ISSUE THREAD

**Issue by tompazourek** [lijunle/Vsxmd#22]
Is it possible to configure the path of the Markdown destination file?

**Comment by lijunle** [comment]
Hi, @tompazourek How do you use the tool? As a MSBuild task, or a single command line?

**Comment by tompazourek** [comment]
Hi @lijunle, I used it exactly as described in the [Usage](https://github.com/lijunle/Vsxmd#usage) section in the documentation.

**Comment by lijunle** [comment]
OK. You can define a project property in your `.csproj` file, named `DocumentationMarkdown` to specify the output path and name.

For example, the follow configuration will output the md file to project root with name `MyMarkdown.md`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!-- other properties ... -->
    <DocumentationMarkdown>MyMarkdown.md<DocumentationMarkdown>
  </PropertyGroup>
</Project>
```

**Comment by tompazourek** [comment]
Thanks! :+1:

**Comment by lijunle** [comment]
You are welcome. :smile:
