### ISSUE TITLE
Doesn't appear to be working with .Net Core.

### ISSUE THREAD

**Issue by roydukkey** [lijunle/Vsxmd#32]
Has this been tested with .Net Core (w/ project.json)? Maybe it would be beneficial to provide usage documentation that would allow manually providing an .xml file to the processor.

**Comment by lijunle** [comment]
Reference this line: https://github.com/lijunle/Vsxmd/blob/master/Vsxmd/targets/Vsxmd.targets#L4

The EXE can be found from the packages folder.

---

I have no idea about how .Net project.json works. Can they consume `.target` build file?

**Comment by roydukkey** [comment]
No. It doesn't appear to use them. http://stackoverflow.com/questions/34922728/whats-the-equivalent-of-nuget-targets-file-in-net-core

**Comment by lijunle** [comment]
It needs time to learn their way. Does the manual EXE script unblock you?

**Comment by roydukkey** [comment]
Yes. I was able to download and compile the exe. It ran with issue. Thanks.

**Comment by lijunle** [comment]
Aha, you can download the `.nuget` file from [the NuGet page](https://www.nuget.org/packages/Vsxmd/), unzip it and get the EXE out of it. Anyway, good to hear that you are unblocked.
