### ISSUE TITLE
In .net core skipped task because DocumentationFile=''

### ISSUE THREAD

**Issue by JuanZamudioGBM** [lijunle/Vsxmd#33]
Building in .net core the output shows this message

`Task "Error" skipped, due to false condition; ( '$(DocumentationFile)' == '' ) was evaluated as ( 'obj\Debug\netstandard2.0\MyFile.xml' == '' ).`

In .net core you don't have to add the name of the documentation file, you just need <GenerateDocumentationFile>true</GenerateDocumentationFile> to generate the xml file.

At the end the file was generated inside obj\Debug\netstandard2.0 but it would be nice to get the md file in the same directory as the xml file

**Comment by lijunle** [comment]
@JuanZamudioGBM  I am sorry that I have not tested the tool in .Net Core. If you want to hack it, you are welcome!

**Comment by lijunle** [comment]
@JuanZamudioGBM Hello, I am not sure if you still using this project. I have some news about .Net Core. The current master branch and CI build is support .Net Core now. The `.targets` file is basically written. Could you please help on testing it?

**Comment by lijunle** [comment]
Now, .Net Core projects are officially supported as of v1.4.1. Please check it.
