### ISSUE TITLE
Incompatibility with VB.NET

### ISSUE THREAD

**Issue by BangL** [lijunle/Vsxmd#34]
## Problem:
![devenv_2018-04-19_16-03-03](https://user-images.githubusercontent.com/551400/38996709-12347624-43ec-11e8-8fbd-1f7d4843bdc9.png)

## Description:
Visual Basic projects do not allow custom paths for the XML file:
![devenv_2018-04-19_16-00-57](https://user-images.githubusercontent.com/551400/38996457-8af5bc18-43eb-11e8-8444-070c4ec925d6.png)

Instead it generates a simple file name for `$(DocumentationFile)`, missing the output path:
![2018-04-19_16-03-47](https://user-images.githubusercontent.com/551400/38996539-b50d7338-43eb-11e8-9872-396ca245892c.png)

`Vsxmd.targets` therefore needs to include `$(OutputPath)` for the `VsxmdCommand` to fix this.

**Comment by lijunle** [comment]
Hmm.. This one is interesting. I never wrote VB.NET before.

@BangL Do you know which `.targets` file generates the documentation file? I feel like that, the doc file generated logic from VB.NET is older than C#.

**Comment by lijunle** [comment]
Close this issue due to no response.
