### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by micdah** [lijunle/Vsxmd#47]
Seems to be limited to Windows only, as it requires the execution of `vsxmd.exe`?

If the program is a .Net application, it might be made to run on macOS by using `mono`?

**Comment by micdah** [comment]
I have confirmed that running using mono seems to work, example:
```
mono ~/.nuget/packages/vsxmd/1.3.1/tools/Vsxmd.exe bin/Debug/netstandard2.0/SlackWebhook.xml ../SlackWebhook.md
```

**Comment by micdah** [comment]
Created #48 which I think should work, though I have not tested it

**Comment by lijunle** [comment]
Will .Net Core help here?

**Comment by micdah** [comment]
Maybe, probably - assuming the target will run via `dotnet` command, it ought to be cross platform

**Comment by saleslessa** [comment]
Hi,
Version 1.3.3 contains this fix.

Thank you.
