### ISSUE TITLE
Not able to use < and > in comments

### ISSUE THREAD

**Issue by wkoeter** [lijunle/Vsxmd#53]
Trying to write common things in code blocks like

```csharp
List<string>
```
or 
```csharp
(param)=>{     }
```
Is currently not possible and gets turned into & gt; and & lt; when using VSXMD

**Comment by lijunle** [comment]
This limitation does not come from Vsxmd. The XML doc is processed by Roslyn compiler.

> https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments

Besides, you can enable code analyzer to check if the compiler warning CS1570 exists.

> https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1570
