### ISSUE TITLE
Generated constructor links do not work

### ISSUE THREAD

**Issue by wkoeter** [lijunle/Vsxmd#54]
When commenting constructor it is also added in **table of contents**.

Example:
#ctor(param1,param2,param3)

When clicking link

Expected: Go to section
Actual: Nothing happens

**Comment by lijunle** [comment]
Hi, @wkoeter I don't understand what is "commenting constructor". Could you please a code snippet to repro this issue?

**Comment by wkoeter** [comment]
A commented constructor as below will produce a link that does not work

```csharp

public class ClassA
{
    /// <summary>
    /// Some summary
    /// </summary>
    public ClassA(string a)
    {

    }
}
```

**Comment by lijunle** [comment]
@wkoeter I still don't understand, I copy the generated ToC and content to [a Markdown file](https://gist.github.com/lijunle/32284760db7809a49d656a9789f0447e). It is working well.

**Comment by wkoeter** [comment]
Both in VS2017 (15.4.4) and in my BitBucket repository the links do not work

**Comment by lijunle** [comment]
From my testing, BitBucket.org completely not supports `<a name=''></a>` tag. How do you get your example working in BitBucket?

**Comment by lijunle** [comment]
Close the issue due to no response.
