### ISSUE TITLE
AppVeyor will fail to build project that uses Vsxmd

### ISSUE THREAD

**Issue by shytikov** [lijunle/Vsxmd#67]
I'm working on **.NET4.5.2** project, using **VS2017**. 

Locally documentation is generated correctly, but when I push files server, AppVeyor picks them up and tries to build. It gets following error:

```\packages\Vsxmd.1.4.1\build\Vsxmd.targets(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.```

Problem is that my <Project> has following format:

```<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">```

so it already has all needed attributes.

Is it possible to fix that so **Vsxmd** could be used on AppVeyor builds as well?

**Comment by lijunle** [comment]
Hi, Alexey

Is your project open source? Is it possible to paste the URL to the related
AppVeyor log?




Alexey Shytikov <notifications@github.com> 于 2019年2月12日周二 23:35写道：

**Comment by shytikov** [comment]
Hej!

Yes, it's opensource. You can read the log using following address: https://ci.appveyor.com/project/shytikov/xrm-utils/builds/22311991

**Comment by lijunle** [comment]
@shytikov Could you please tried to declare VS2017 in your project's [`appveyor.yml`](https://github.com/Innofactor/Xrm.Utils/blob/master/appveyor.yml) file?

https://github.com/lijunle/Vsxmd/blob/7d4a456c16def713edf834dc5487ec7212b190a8/appveyor.yml#L3-L4

**Comment by shytikov** [comment]
Thank you! That seems to be resolved my issue!
