### ISSUE TITLE
`Vsxmd.targets` is not compatible with VS2015

### ISSUE THREAD

**Issue by benjspriggs** [lijunle/Vsxmd#68]
I'm running into an issue installing Vsxmd for a .NET framework project using Visual Studio 2015. It looks similar to [this issue](https://github.com/Microsoft/ClearScript/issues/74) and looks like a simple fix.

## repro

1. Install Vsxmd@1.4.1 via nuget for VS2015 project
1. Observe the following error:

> Fail to install. Message:The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\v-bespri\source\repos\OfflineMetrics\private\nuget\packages\Vsxmd.1.4.1\build\Vsxmd.targets

**Comment by lijunle** [comment]
@benjspriggs I just released the version [1.4.2](https://www.nuget.org/packages/Vsxmd/1.4.2) to contain your fix. Please help to validate it once it can be downloaded from NuGet. Thanks on contributing this project!

**Comment by benjspriggs** [comment]
Thanks for your prompt response @lijunle, I've installed 1.4.2 for my project via Nuget and updating the namespace for the `.targets` file *did work*!

I'm not sure that in future versions, the `xmlnamespace` will be preserved, but it will definitely allow VS2015 consumers (on .NET 4.6) to be able to use this library via Nuget in the future.

I'll close this since this issue's been addressed, thanks again!

**Comment by lijunle** [comment]
Great to hear that is working!

It will not intentionally to remove the namespace attribute, but you know, without CI guarantee, it is hard to ensure future changes working in VS2015/MSBuild14.
