### ISSUE TITLE
Getting `command exited with code -2147450726` for `Vsxmd.exe`

### ISSUE THREAD

**Issue by astrohart** [lijunle/Vsxmd#92]
I am writing an application that is targeting .NET Framework 4.8 -- and the following is a compiler error I am receiving on each of the supporting class libraries (this is just from one of them):

```
The command ""C:\Users\Administrator\source\repos\MyRepo\MySolution\packages\Vsxmd.1.4.5\build\/../tools/win-x64/Vsxmd.exe" "bin\Debug\MyClassLibrary.xml" "" """ exited with code -2147450726.		
```

What could be causing this?

I've made sure to have the latest .NET Framework, .NET Core runtimes installed and I also used the Visual Studio Installer to make sure 

I've deleted the `packages` folder and done `Update-Package -Reinstall` in Package Manager Console, to no avail.  The solution contains 60+ projects, so I am not willing to convert them to `PackageReference` since there is no functionality in Visual Studio to do a mass conversion of all projects that need it; you have to do them one by one, by hand.

Any thoughts?

Brian Hart

**Comment by astrohart** [comment]
Opening a Command Prompt window 'as administrator', with VS2019 open, and doing:

```
C:\>RD /S /Q "%TEMP%"
```
and pressing `ENTER`, made the error messages go away.

**Comment by Elanis** [comment]
> Opening a Command Prompt window 'as administrator', with VS2019 open, and doing:
> 
> ```
> C:\>RD /S /Q "%TEMP%"
> ```
> 
> and pressing `ENTER`, made the error messages go away.

Note: you don't need to remove the whole temp directory, but only the `.net/Vsxmd` subdirectory

**Comment by astrohart** [comment]
> > Opening a Command Prompt window 'as administrator', with VS2019 open, and doing:
> 
> > 
> 
> > ```
> 
> > C:\>RD /S /Q "%TEMP%"
> 
> > ```
> 
> > 
> 
> > and pressing `ENTER`, made the error messages go away.
> 
> 
> 
> Note: you don't need to remove the whole temp directory, but only the `.net/Vsxmd` subdirectory

Good point.  

However, I have found that this command usually is quicker to run.  

Also, any files that are still in use by other applications will not be removed.  

Furthermore, in my post above, I forgot to add that it helps to exit out of all open Visual Studio instances first --- before running the command.
